### ISSUE TITLE
Awesome!  Any plans for other *nix compatibility?

### ISSUE THREAD

**Issue by bglusman** [Homebrew/homebrew-bundle#1]
We had plans for a project a little like this but the idea was to make it cross platform so if you develop on Mac and deploy to Linux, dependencies would install and resolve properly in both places...  currently of course Homebrew is Mac only, but I saw someone has an experimental Solaris port of homebrew (https://github.com/rmyers/homebrew)... Curious if this is a personal itch you'd like to scratch as well, and if so, I know some people (myself included) who'd like to help if we can!

**Comment by adamliter** [comment]
@andrew I just tried running `brew bundle` on a Linux machine (Ubuntu 14.04), and I get the error:

    /usr/bin/env: ruby -W0: No such file or directory

The odd thing is that explicitly typing `/usr/bin/env ruby -W0` at the command line works. I'm honestly not really sure why the shebang isn't working, and I don't know what to do in order to debug this, especially since it works when manually typing the shebang.

**Comment by mikemcquaid** [comment]
@adamliter I'm afraid I don't know what to suggest here beyond trying to submit a pull-request.

**Comment by adamliter** [comment]
@mikemcquaid @andrew 
It seems that the problem is that the system is trying to call the executable "ruby -W0". See this [Stack Overflow question](http://stackoverflow.com/q/24032641/2571049) and its [answer](http://stackoverflow.com/a/24032743/2571049).

That being said, I have no idea why this works on a Mac but not Linux.

According to this [Ruby forum post](https://www.ruby-forum.com/topic/96121#199230), the best practice for shebangs with arguments in Ruby is to do:

```sh
#!/bin/sh
exec ruby -x "$0" "$@"
#!ruby -W0
# Ruby code goes here ...
```
If this is something you're open to changing, I'm happy to submit a pull request.

I tested it on both a Mac (10.10.5) and Ubuntu (14.04), and this seems to work in both cases.

**Comment by mikemcquaid** [comment]
@adamliter Yeh, feel free to submit a PR. We could probably just try `#!/usr/bin/env ruby`.

**Comment by adamliter** [comment]
@mikemcquaid I've created the pull request using the solution I suggested. I haven't tested it, but your suggested solution of just using `#!/usr/bin/env ruby` should also work. If you'd rather do that, I can change the pull request, or you can just close the pull request and make the changes yourself, if that's quicker. Thanks! :smile:

**Comment by Nakilon** [comment]
I wonder why the options in shebang fail my ruby gem linux build in travis but when I do similar thing as first line in Jenkins steps it works fine in Ubuntu and CentOS.
