### ISSUE TITLE
Feature request: Auto-start a cask after installation

### ISSUE THREAD

**Issue by vraravam** [Homebrew/homebrew-bundle#1306]
I was hoping that once brew installs a cask, there would also be a mechanism to start the app. This is super useful proceed with using the app as soon as the installation is successful. This could be similar to the `restart_service` option in the Brewfile as an optional config parameter. If this is ok, I would be willing to raise a PR for the same. wdyt?

This is not the same as the `at_exit` hook imho, since that is run once at the end of ALL installations. But, what I'm requesting is for each cask line to have the ability to start the application (so it need not be done for all apps that get installed - leaving that to the user's choice). Also, I'm not sure if `at_exit` runs if there's an error at an earlier point while installing from a Brewfile

**Comment by SMillerDev** [comment]
I think this first requires a way for brew to start a cask independently of `brew bundle`

**Comment by vraravam** [comment]
> I think this first requires a way for brew to start a cask independently of `brew bundle`

did you mean for such a feature to be supported from the cmd-line brew first, and only then from the Brewfile's DSL?

**Comment by SMillerDev** [comment]
Yeah, since the Brewfile DSL just runs brew functions under the hood.

**Comment by vraravam** [comment]
I see various references to `Bundle.system` in this repo. I was thinking that would be the way to use the `open` command on macos to start the application. Wouldn't that suffice?

**Comment by SMillerDev** [comment]
But how does one start a cask. How do you know what to start?

**Comment by vraravam** [comment]
> But how does one start a cask. How do you know what to start?

`open` command on macos like so: `open /Applications/KeePassXC.app`

**Comment by SMillerDev** [comment]
But a lot of casks are pkg files, or contain multiple apps. So that will create an experience where it's just a gamble if it'll work

**Comment by vraravam** [comment]
if that's the case, then my suggestion would be to let the user specify a system command to execute upon successful completion of the installation of each cask. That allows the flexibility to the user and they can choose to open 1 or more of those apps. Could we pivot to that?

**Comment by jacobbednarz** [comment]
sorry, but I'm a 👎 on this feature request for a couple of reasons. 

1. you don't "start" a cask. you _install_ a cask which then extracts all the nessecary parts into your system. what you're talking about here is more related to services and being able to launch them. if you want this, I'd suggest looking at the individual cask/formula and seeing if it can be included in there. this is something that is already supported. 
2. as @SMillerDev mentioned, a cask isn't always a single executable and expecting the user to know which they want to target is unreasonable. similarly, it's unreasonable for bundle to guess as getting the wrong information is worse than not doing it at all since you've then incorrectly taken the user down another path.

**Comment by MikeMcQuaid** [comment]
Passing on this for now, sorry!
