### ISSUE TITLE
Support for `uv`

### ISSUE THREAD

**Issue by martimlobao** [Homebrew/homebrew-bundle#1477]
[`uv`](https://github.com/astral-sh/uv) is, among other things, becoming an extremely popular way to run and install Python-based tools like `ipython`, `mypy` or `sqlfluff`. Adding support for `uv` in Brewfiles would be a nice addition.

**Comment by jacobbednarz** [comment]
generally, we want to have multiple requests before we add any new ecosystem support for things like this to avoid building things that don't benefit others more broadly.

given it's not the pseudo standard today, i'd also be hesitant in adding support until it gains more usage.

**Comment by martimlobao** [comment]
> generally, we want to have multiple requests before we add any new ecosystem support for things like this to avoid building things that don't benefit others more broadly.
> 
> given it's not the pseudo standard today, i'd also be hesitant in adding support until it gains more usage.

That's a very valid concern. I have a couple of questions:
1. I've taken a look at the repo and at least at first glance, it seems relatively straightforward to add support myself (seems like mostly just adding a different version of these files [1](https://github.com/Homebrew/homebrew-bundle/blob/master/lib/bundle/mac_app_store_dumper.rb) [2](https://github.com/Homebrew/homebrew-bundle/blob/master/lib/bundle/mac_app_store_checker.rb) [3](https://github.com/Homebrew/homebrew-bundle/blob/master/lib/bundle/mac_app_store_installer.rb) [4](https://github.com/Homebrew/homebrew-bundle/blob/master/spec/bundle/mac_app_store_dumper_spec.rb) [5](https://github.com/Homebrew/homebrew-bundle/blob/master/spec/bundle/mac_app_store_installer_spec.rb)). Does this seem like a somewhat reasonable task to you or am I potentially overlooking something that might make this much more difficult?
2. If I did do that, would creating a PR for this be worthwhile or is there still a concern that doing so will bring the need to maintain this going forward?

**Comment by jacobbednarz** [comment]
if we decided this was worth adding, a PR is always welcome. 

for me, i don't yet think we have enough of a request backlog for `uv` being included so i would probably pass based on my knowledge of it today. personally, this gives a higher signal that we need an agnostic plugin system that gets all of these requests out of core bundle and allows folks to hook into ecosystems if they choose to without additional core support for these things.

**Comment by martimlobao** [comment]
A plugin system for custom support sounds like an awesome idea!

**Comment by MikeMcQuaid** [comment]
> [`uv`](https://github.com/astral-sh/uv) is, among other things, becoming an extremely popular way to run and install Python-based tools like `ipython`, `mypy` or `sqlfluff`.

These tools all exist in Homebrew already. Why would you want to install them using `uv` but still through `brew` (bundle`)?

I'm not strongly opposed (yet!) but I do think it makes sense to avoid overlapping ecosystems here.

**Comment by martimlobao** [comment]
> > [`uv`](https://github.com/astral-sh/uv) is, among other things, becoming an extremely popular way to run and install Python-based tools like `ipython`, `mypy` or `sqlfluff`.
> 
> These tools all exist in Homebrew already. Why would you want to install them using `uv` but still through `brew` (bundle`)?
> 
> I'm not strongly opposed (yet!) but I do think it makes sense to avoid overlapping ecosystems here.

This is true, and it was something I considered when deciding whether to install them using using `brew` or `uv`. The main reason I chose to go with `uv` is that it allows you to install virtually _any_ python package, including things that aren't available on Homebrew, such as [airflow](https://github.com/apache/airflow) or [marimo](https://github.com/marimo-team/marimo). Obviously, for things like `ipython` which are also available on Homebrew I could have gone with either option, but for consistency's sake I find it easier to install all Python packages using the same tool.

The reason for using `bundle` is merely for the convenience of a reproducible setup without having to build my own tooling to achieve something that has already been done.

**Comment by MikeMcQuaid** [comment]
Ok, thanks for explaining I think we'll pass on this for now but: anyone else who wants `uv` for this: shout and we're more likely to consider.

Would definitely be game to accept a PR to add a plugin system here though, @martimlobao!

**Comment by MikeMcQuaid** [comment]
> installing tools (like marimo) is.

@lemeb out of interest: why would installing this with `uv` rather than `brew` be better?

**Comment by colindean** [comment]
I'm tepid on this idea, leaning toward a _not yet_ for `uv` but not a _never_.

## uv

I'm not sure yet on uv's installation and management of its own Python, and what support burden that might shift to Homebrew. uv is also maturing rapidly but not yet 1.0.0, so things may change. I'd be warmer on the idea when it achieves that stability. @MikeMcQuaid has a far better concept of these risks, however major or minor they may be.

## pipx

I think it's in-bounds to add `pipx` support that would:

1. ensure `pipx` is installed with `brew install pipx`, this would install+use Homebrew's managed Python because of `PIPX_DEFAULT_PYTHON=/opt/homebrew/opt/python@3.13/libexec/bin/python`
2. install a package with `${brew_prefix}/pipx install ${package}`

```ruby
pipx 'ruff'
```

## ideal

I like the idea of having something like this for installing ruff [^yesiknow]:

[^yesiknow]: Yes, I know Ruff has a Homebrew formula, it's just the first thing that comes to mind that's installable with pipx and uv in this mode.

```ruby
# set which to use
use_mgr :python, 'uv'
use_mgr :python, 'pipx'
# invoke with
python "ruff"
# or maybe this, with ':using' having a default of pipx?
python "ruff", using: :uv
python "ruff", using: :pipx
```
but this may be too abstract for real needs and the lift would be far greater to implement and maintain.

## UX

But in the face of this, what's easier for the user?

1. `pipx "mypackage"`
2. Build a formula using [the Python instructions](https://docs.brew.sh/Formula-Cookbook#python-dependencies) and put the formula in a (new) tap or upstream it?
3. Use my favorite [`at_exit`](https://github.com/Homebrew/homebrew-bundle/issues?q=is%3Aissue+at_exit+) to take actions after `brew bundle` runs, including running `uv tool install` or `pipx install`.

**Comment by MikeMcQuaid** [comment]
> but this may be too abstract for real needs and the lift would be far greater to implement and maintain.

Yes, sorry. Let's keep `pipx`/`ruff` out of the scope of this issue and focus on `uv`, please.

**Comment by colindean** [comment]
I'm also in support of a plugin system. That'd be a neat power to gain because there are some other ecosystems requested that just don't have enough support for us to maintain.
