### ISSUE TITLE
Directory of Brewfiles?

### ISSUE THREAD

**Issue by cweagans** [Homebrew/homebrew-bundle#158]
My use case is that I'm using Stow to manage my dotfiles. If I do `stow zsh` to symlink my zsh config files, I might create `~/.config/homebrew/Brewfile.zsh`. After I run `stow` on all of my packages, it would be really cool to be able to just do `brew bundle --dir=~/.config/homebrew` and have all of my dependencies installed automatically.

If this is not possible in the main homebrew-bundle project, is there at least some way to have `~/Brewfile` include/require other brewfiles?

Sorry if this is a weird request. I'm trying to break my dotfiles up into separate components without strict dependencies on other components.

**Comment by cweagans** [comment]
As a basic example, I tried putting these files in the same directory:

Brewfile:
```
brew 'readline'

load "Brewfile.subfile"
```

Brewfile.subfile:
```
brew 'xz'
```

and then ran `brew bundle`. I also tried it with `require` and `include` in the main `Brewfile` instead of `load`, but nothing worked.

I'm a bit of a Ruby n00b, so if I'm doing something dumb, feel free to break out the clue-by-four.

**Comment by UniqMartin** [comment]
`require` and `load` only work if the referenced file is in Ruby's `LOAD_PATH` (a concept similar to `PATH` in the shell) or if the full path is given. `include` does something completely different. Since a `Brewfile` is just Ruby code, you can do something like this to load all `Brewfile.*` files in a directory:

```ruby
Dir["#{File.dirname(__FILE__)}/Brewfile.*"].each do |sub_file|
  load sub_file
end
```

This will locate the files relative to the main `Brewfile` and in the order they are returned by `Dir[]`.

**Comment by mikemcquaid** [comment]
As @UniqMartin said this should be possible with `require` or `load` from Ruby. Feel free to keep talking in here but closing this out. Thanks!

**Comment by REBELinBLUE** [comment]
@cweagans Were you ever successful in getting this working? I am doing something similar, I have tried the code above but I just get

```Error: Invalid Brewfile: wrong number of arguments (1 for 0)``` but if I run each file individually with

```brew bundle --file=Brewfile-work``` it is fine

**Comment by UniqMartin** [comment]
@REBELinBLUE What are the contents of your primary `Brewfile` (that, I suppose, is loading the others)? Have you copied my above snippet verbatim? What are the file names of the other `Brewfile`s you'd like to load from there?

**Comment by REBELinBLUE** [comment]
Well mine is slightly different. I have 3 files `all`, `work` and `personal`

https://github.com/REBELinBLUE/dotfiles/blob/master/brewfiles/all is my main file, I was trying to include it in https://github.com/REBELinBLUE/dotfiles/blob/master/brewfiles/personal and https://github.com/REBELinBLUE/dotfiles/blob/master/brewfiles/work by using

`load 'all'` at the top but that gave me there error, so I renamed it to Brewfile.all just to try your snippet and used that instead and I still got the error, but if I run any of the files separately I don't get the error

**Comment by UniqMartin** [comment]
`load` requires a full path (or the file needs to be in Ruby's search path, something that doesn't make sense for the `Brewfile`s). Can you try `load "#{File.dirname(__FILE__)}/all"` instead of `load 'all'`?

**Comment by REBELinBLUE** [comment]
Sorry, I should have said I tried that as well

**Comment by cweagans** [comment]
I'll post my Dotfiles later. Mobile right now. If I haven't replied here in 24 hrs, feel free to nag me publicly :)

**Comment by UniqMartin** [comment]
I just checked and realized that the suggested approach cannot work because of how `brew bundle` reads and processes a `Brewfile`. I don't think there's currently a viable way to include a `Brewfile` from another. Making that work would require quite a few changes to the internals of `brew bundle`.

There several options as far as I can tell:

- Use something like `cat Brewfile.* | brew bundle --file=-` to concatenate a bunch of `Brewfile`s and to pass them to `brew bundle`. (This should work right now, but is admittedly a bit ugly.)
- Implement `--dir=` as an alternative to `--file=` that would process all files from the given directory  (as described in the top comment).
- Implement another directive alongside `brew`, `cask`, and `tap` that can be used in a `Brewfile` and allows including the contents of another file.

(The latter two options would require someone to step up and implement this. As I'm not a maintainer of this project, I cannot say whether any of those additions is preferable and if it would be accepted.)

**Comment by REBELinBLUE** [comment]
Ah well never mind, thanks anyway for your help

**Comment by cweagans** [comment]
Ah, yeah, looking at it now, I am concatenating the brewfiles together as part of a shell script.

**Comment by mikemcquaid** [comment]
> Use something like cat Brewfile.* | brew bundle --file=- to concatenate a bunch of Brewfiles and to pass them to brew bundle. (This should work right now, but is admittedly a bit ugly.)

I think this is the preferred option as it's a relatively niche use-case.

**Comment by CNG** [comment]
Thanks for the tip. I think I will be using a command like `find -H . -name 'Brewfile' -print0 | xargs -0 cat | brew bundle --file=-`, then. I haven't used `brew bundle` before, so am looking to work it into my process now!
