### ISSUE TITLE
Allow only installing missing formulae without upgrading existing ones

### ISSUE THREAD

**Issue by mislav** [Homebrew/homebrew-bundle#229]
I'm a big fan of having a Brewfile in my home directory (and keeping it in version control) and using `brew bundle --global` to ensure I have all the utilities and apps I need. However, because my Brewfile lists formulae I use for development such as `node` and `go`, I don't want these to be auto-upgraded when I run `brew bundle` to fill in the blanks, i.e. install the new additions I made to my Brewfile. I only ever want formulae to be upgraded when I issue an explicit `brew upgrade`.

Now, I know about pinning and yes, I could easily `brew pin node go` to prevent them from being auto-upgraded. But, on principle, I kind of don't want `brew bundle --global` to ever upgrade *any* of the formulae. That means I would have to pin them all, which would make manual upgrades more clumsy since I'd have to go through an unpin-upgrade-repin dance.

I also know about `homebrew/versions`, and while I see it very useful for project-specific Brewfiles shared between a team of people, I feel it's an overkill for my own personal needs, where I simply want to install the latest version of e.g. `node` when I set up a fresh computer, but have control over when it's upgraded.

I've created [a workaround for myself](https://github.com/mislav/dotfiles/commit/7a05ec98779b25981c91526f19782aaaf274c183) that temporarily pins everything before `brew bundle`, and restores previously pinned on completion, but that makes me wish that `brew bundle` had some kind of `--no-upgrade` option.

Does this feature make sense for anyone else, or was `brew bundle` envisioned with a different set of principles in mind?

**Comment by MikeMcQuaid** [comment]
> was brew bundle envisioned with a different set of principles in mind?

The main reason for this current behaviour is that `brew bundle` is unable due to Homebrew constrains to offer a e.g. `Brewfile.lock` so it's ensuring that a given team that all runs `brew bundle` will end up using the same version at the end for consistency.

That said, I can see your use-case here and will leave this open for a while to see what others think.

**Comment by jeremy** [comment]
We've been using a Brewfile for our projects for a few months now and I've gotten a lot of ~feedback~pushback about the extra churn caused by always upgrading. It can cause a bunch of extra work at an inopportune time: dev adds a new dep, installs, also gets a new redis and mysql, throws computer out window, etc 😊

I'd like to see a conservative `brew bundle` paired with a "float to latest everything" `brew bundle upgrade` (or similar).

**Comment by MikeMcQuaid** [comment]
@jeremy My thinking when using it for projects you do want to have a `brew bundle` perform upgrades so that your project has consistent versions. You can view it similarly to a `Gemfile.lock` where the locks are on the latest version. This means that two people running `brew bundle` at the same time will end up on consistent versions.

> also gets a new redis and mysql

At GitHub we're using e.g. https://github.com/Homebrew/homebrew-versions/blob/master/mysql56.rb for these cases. Homebrew itself is working to improve versions support but I think setting up your `Brewfile` with the assumption that a `brew upgrade` isn't going to be painful is the best bet. Definitely open to your thoughts there, though.

**Comment by jeremy** [comment]
@MikeMcQuaid Yeah, totally makes sense—on board with this thinking from the start 😊 Just keeping an eye open to patterns in our users' experience.

> setting up your Brewfile with the assumption that a brew upgrade isn't going to be painful is the best bet

Hear, hear 🍻
