### ISSUE TITLE
Feature Request: subcommands to add/remove packages

### ISSUE THREAD

**Issue by tycobbb** [Homebrew/homebrew-bundle#365]
It would be nice for `brew bundle` to include subcommands to install/uninstall packages while keeping corresponding Brewfile up-to-date. Something similar to the add/remove functionality in bundler or npm. 

Is this feature significant enough to be considered for inclusion? If it's not high-enough priority, would a PR be accepted?

### Motivation
While `brew bundle` is great, keeping a Brewfile updated independent of the normal brew installation procedure is tedious/error-prone. It is especially painful when trying to maintain a consistent environment across multiple machines. 

A personal use-case: when testing new tools I tend to install and then quickly remove them once I decide they don't meet my needs. I'm inconsistent remembering, once I decide to keep them, to also update my global `.Brewfile`. The environments on my machines tend to slowly diverge.

### Proposal
Add two subcommands to `brew bundle`:

```sh
brew bundle add <package-name>
brew bundle remove <package-name>
```

Any `brew bundle` options would be applied to map to the correct Brewfile. The rest of the options could be passed through to the root install/uninstall commands.

#### Alternatives
Add npm-like `--save=<brewfile>` and `--save-global` options to `brew install`
- `+` Surfaces `brew bundle` functionality to more users. It's great, but hard-to-discover right now
- `-` Can't think of an unsurprising way for `brew uninstall` to clean up the correct Brewfile
- `-` Top-level commands now require a plugin, inverts control

Use `install/uninstall` instead of `add/remove` to maintain core `brew` jargon
- `-` Install already has a different meaning for `brew bundle`
- `-` Doesn't signal the Brewfile mutation as well as `add/remove`

**Comment by colindean** [comment]
I would very much like this feature.

**Comment by MikeMcQuaid** [comment]
> Is this feature significant enough to be considered for inclusion? If it's not high-enough priority, would a PR be accepted?

Given @colindean is 👍: yeh, I think it'd be suitable to at least take a look at a potential implementation. Personally I don't see it being much easier than adding the line manually to the `Brewfile` but I guess I'm not the target audience for this feature and if `bundler` and `npm` have something similar that's a decent argument for it.

Bear in mind you'll need to figure out a syntax to be able to add `brew`/`tap`/etc. lines and ideally specify options as well.

**Comment by colindean** [comment]
I think it could work explicitly and implicitly.

## Explicit operation

    brew bundle add packagename
    brew bundle add packagename --with-only-the-best-options
    brew bundle add cask packagename
    brew bundle add tap orgname/reponame
    brew bundle add mas 42421337 appname

I like longer, more explicit terms like `record` or `persist` but that's like three more characters so whatever  ¯\\\_(ツ)_/¯

This follows the form of

    brew install packagename
    brew install packagename --with-only-the-best-options
    brew cask install packagename
    brew tap orgname/reponame
    mas 42421337 appname # I think? I've never actually used it outside of homebrew.

This could get a little complex but I think it kinda follows a convention.

## Implicit operation

If an environment variable like `HOMEBREW_BUNDLE_FILE` or `BREWFILE` is defined, then _any_ installation operation will append to it and any uninstall operation will _tell the user_ of the package's existence in the Brewfile.

That is,

    BREWFILE="~/Source/Dotfiles/Brewfile" brew install packagename

will add `packagename` to the specified Brewfile, perhaps only if it doesn't already exist.

   BREWFILE="~/Source/Dotfiles/Brewfile" brew cask install packagename

would operate the same, as would `brew tap orgname/reponame`.

It'd be up to the user to periodically evaluate what they've implicitly added. This is no different from reviewing while committing (e.g. `git commit -v`) or during a PR.

Use of `mas` would be out of scope unless someone came up with a wrapper, e.g. `brew mas`.

Hehe, brewmas. Ho ho ho. 🎅 🎁 

## Other stuff

I'm OK with `brew bundle remove` not existing, certainly at first, maybe not ever. MVP would be that I can install something and "know" that it's added to my global list of intentionally installed things, tracked therein in my `Brewfile`.

I'm not a huge fan of something like `brew install --save packagename` but I could see that option being an _explicit_ feature as a part of a _transition_ toward an absolute "If you have defined `BREWFILE`, we're gonna write to it" contract. 

Aside: I frankly wish that `npm` worked like `cargo` in that I had to manually specify dependencies but can do `cargo install packagename` and the binaries of `packagename` are on my path in due time. Aside #2: I want more things like [`brew-gem`](https://github.com/sportngin/brew-gem) because I want _one_ source of installer for binaries on macOS like apt/yum/etc. on Linux but whatever, lol.

Presently, `brew bundle` is _not_ read-only: `brew bundle dump` outputs directly to `Brewfile` in the cwd unless `--global` is passed, in which case it outputs to `~/.Brewfile`. I've not verified if it _overwrites_ those files, though. There's a part of me what wants `brew bundle` operations to be read-only but I also acknowledge that our user workflows may not account for the user redirecting output.

## Final notes

Whatever happens, it should be explicit or transparent, or both, dependent on user intent as expressed by environment variables. If the user is OK trusting Homebrew to modify their Brewfile with wanton abandon, then 👍. If the user is OK typing a bit more to explicitly track the packages they've installed, I'm OK giving them a nice interface lets them choose how Homebrew modifies their Brewfile.

**Comment by MikeMcQuaid** [comment]
@colindean Neat idea but I think making the simplest solution first and iterating would be better 👍

**Comment by colindean** [comment]
Absolutely.

**Comment by musaprg** [comment]
Is anyone still working on this feature?

**Comment by MikeMcQuaid** [comment]
@musaprg No. `help wanted` generally means no maintainers are working on it but we welcome PRs to help.

**Comment by musaprg** [comment]
@MikeMcQuaid Thanks for replying:sparkles: I'd like to try it because I need this feature as well. Can I work on it?

**Comment by MikeMcQuaid** [comment]
@musaprg Yes, please!

**Comment by MikeMcQuaid** [comment]
Closing as this is stale at this point but we'd consider a PR.
