### ISSUE TITLE
A failing line in Brewfile should throw an exception, not exit

### ISSUE THREAD

**Issue by colindean** [Homebrew/homebrew-bundle#456]
My new employer seems to block sign-in to the App Store – I cannot for the life of me get it to sign in – so I cannot proceed without editing my Brewfile.

I have had this in my Brewfile for a while:

```
begin
  mas 'Trello', id: 1278508951
rescue
   echo "mas is unavailable, skipping Mac App Store apps"
end
```

I kinda expect it to work: a line shouldn't fail out, it should either continue or throw an exception. Right now, bundle exits when a line – at least a `mas` line – fails.

**Comment by colindean** [comment]
That code above would have _never_ worked because of how the DSL works. The DSL doesn't actually execute each line as an operation, rather, it adds an entry to a list of entries when parsed. E.g. when calling [`mas`](https://github.com/Homebrew/homebrew-bundle/blob/d2b0decad910b5ba117dbe29949ceb9861a34271/lib/bundle/dsl.rb#L58).

Nonetheless, I think there is room for a mode – even default operation – that allows the Brewfile installation to continue by modifying here:

https://github.com/Homebrew/homebrew-bundle/blob/d2b0decad910b5ba117dbe29949ceb9861a34271/lib/bundle/installer.rb#L29-L39

This could be inside of an exception handler.

**Comment by MikeMcQuaid** [comment]
This seems like a reasonable request as long as all the errors are output at the end to avoid people missing their output.

**Comment by MikeMcQuaid** [comment]
Re-reading this again I'm not sure I agree it's a reasonable request. If you're handling internal exceptions that Homebrew Bundle itself throws you're silently ignoring a bad `Brewfile` format. As that's not causing the error here: can you elaborate on what is specifically?

> Right now, bundle exits when a line – at least a `mas` line – fails.

Can we see the full output here? It's not going to happen when it just fails to install.

> so I cannot proceed without editing my Brewfile.

Honestly: this seems expected behaviour on second look. If you're telling Homebrew Bundle to install from `mas`: why should it not fail if it cannot sign in?

**Comment by colindean** [comment]
```
[14:48:47 z003xc4@f0189898cc36 /tmp ]
$ cat Brewfile
mas 'Trello', id: 1278508951
brew "openssl"
[14:48:56 z003xc4@f0189898cc36 /tmp ]
$ brew bundle
Error: Unable to install Trello app. mas not signed in to Mac App Store.
[14:49:05 z003xc4@f0189898cc36 /tmp ]
$ echo $?
1
```

I would expect it to output `Using openssl` before exiting. 

> If you're telling Homebrew Bundle to install from mas: why should it not fail if it cannot sign in?

Ultimately, I think my goal here is to somehow indicate that Bundle should continue installing things when there's an exception because `mas` isn't or can't be signed in, regardless of if that exception occurs at DSL parse time or task execution time.

Maybe we have differing expectations: I expect that Bundle should do the work that it can and report the work that it cannot so that the user can act on the problem. 

This raises the question: what should the workflow be when a user _can't_ resolve the problem by means other than effectively removing the affected dependency from the Brewfile?

The implication for me at the moment is that I'd have to keep my `mas` deps in another file _or_ have some logic in my Brewfile that determines the environment in which the Brewfile is executing (e.g. looks at hostname, envvar, etc.) and omits any `mas` dependencies if the Brewfile is executing on my work computer since `mas` will never work on it.

**Comment by MikeMcQuaid** [comment]
> Ultimately, I think my goal here is to somehow indicate that Bundle should continue installing things when there's an exception because `mas` isn't or can't be signed in, regardless of if that exception occurs at DSL parse time or task execution time.

The exception in this case is deliberately thrown by the application so instead of rewriting a bunch of the application if we want to avoid this terminating the application early it could not throw the exception but instead print out a warning/error message.

> Maybe we have differing expectations: I expect that Bundle should do the work that it can and report the work that it cannot so that the user can act on the problem.

The purpose of a `Brewfile` is to bring the user to a given state in order to perform a task. If that state cannot be achieved I'm not sure it really matters hugely to what proportion the task has been achieved or not. Often some items in a `Brewfile` depend on others to be installed (which is why we're careful with the ordering of `brew bundle dump`).

> This raises the question: what should the workflow be when a user _can't_ resolve the problem by means other than effectively removing the affected dependency from the Brewfile?

They always can.

> The implication for me at the moment is that I'd have to keep my `mas` deps in another file _or_ have some logic in my Brewfile that determines the environment in which the Brewfile is executing (e.g. looks at hostname, envvar, etc.) and omits any `mas` dependencies if the Brewfile is executing on my work computer since `mas` will never work on it.

Yes.

**Comment by MikeMcQuaid** [comment]
Passing on this in favour of one of the approaches discussed in here or https://github.com/Homebrew/homebrew-bundle/pull/486

**Comment by MikeMcQuaid** [comment]
@colindean Now https://github.com/Homebrew/homebrew-bundle/pull/486 is merged you may find it useful for your use-case.
