### ISSUE TITLE
Fix English

### ISSUE THREAD

**Issue by conatus** [Homebrew/homebrew-bundle#51]
Thanks for working on this!

The output for the main command seems a little off in terms of idiomatic English.

```
Succeed to install <thing>
```

Should be something like:

```
Successfully installed <thing>
Failed to install <thing>
Tapped <thing>
```

I will try and sort this if I have a spare moment - the relevant line is https://github.com/Homebrew/homebrew-brewdler/blob/7d9be9deb2601247136e0ce2b526ae0c1e7a7ada/lib/brewdler/dsl.rb#L41-L47

For the future it might be nice to have these strings generally translated.

**Comment by andrew** [comment]
:+1: that would be a nice little improvement

**Comment by cisso** [comment]
I think "Successfully ran X" and "Failed to run X"  would be enough. If I'm not mistaken Brewdler can't know all possible commands up front, and proper flexing might be a bit too much to ask for. 

For some sort of Poorman's flexing, how about matching the last characters of the verb and map them to a suffix / replace them, otherwise default to appending "ed"? 
An initial map could look like this:
    {'p'=>'pped', 't' =>'t', 'e' =>'ed'  }

**Comment by mikemcquaid** [comment]
This was fixed.
