### ISSUE TITLE
Brew bundle check doesn't take taps into account

### ISSUE THREAD

**Issue by ffittschen** [Homebrew/homebrew-bundle#702]
If I add a formula from a tap to the Brewfile that has the same name as a formula in homebrew-core, `brew bundle check` will not check if the installed binary is from the tap or homebrew-core.

### Example

<details open>

<summary>Brewfile</summary>

```ruby
tap "nsoperations/formulas"

brew "nsoperations/formulas/carthage"
```

</details>

```bash
# Given the above Brewfile and I install carthage from homebrew-core
$ brew install carthage

# When I run brew bundle check now
$ brew bundle check --file Brewfile

# Then Homebrew says all dependencies are satisfied
The Brewfile's dependencies are satisfied.
```

I'd expect to Homebrew to uninstall the existing formula and install the formula from the tap. Would this be a reasonable change? If I get some pointers into the right direction, I'd be happy to submit a PR with the changes

**Comment by MikeMcQuaid** [comment]
This is Homebrew issue rather than a Homebrew/bundle issue as Homebrew will show the `carthage` formula as up-to-date if the versions match.

This is why we recommend naming formulae in taps that shadow homebrew/core differently: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#naming-your-formulae-to-avoid-clashes.

I'll certainly review a PR to address this but I'm not sure what it should do, really. I guess it could check the tap matches and reinstall if it doesn't in Homebrew/bundle? Closing because this is a WONTFIX for maintainers but let's keep discussing a PR here.
