### ISSUE TITLE
Dump should handle dependencies order.

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew-bundle#74]
`brew bundle dump` should handle entry order based on dependencies. The dependencies of a formula should come first.  At the same time, requirements from cask like `java`, `mactex` should come first as well. But some casks should come later for those depend on formula.

**Comment by xu-cheng** [comment]
Or should we handle this in install rather than dump?

**Comment by mikemcquaid** [comment]
I think either would be good. Also: `cask` should probably assume that `brew-cask` is installed and install it if not. I noticed this the other day.

Some people (I can't remember the issue or if it was somewhere else) suggested that dependencies should be implicit in the `dump` so that they don't need to be entered there and `dump` just shows basically `brew leaves`. Dunno what you think about that?

**Comment by xu-cheng** [comment]
> cask should probably assume that brew-cask is installed and install it if not. I noticed this the other day.

Good idea.

> that dependencies should be implicit in the dump so that they don't need to be entered there and dump just shows basically brew leaves. 

Personally, I don't think it's much useful feature. On the contrary, it will complicate the implementation.

**Comment by mikemcquaid** [comment]
:cool:

**Comment by danielbayley** [comment]
@mikemcquaid 
> Some people suggested that dependencies should be implicit in the dump so that they don't need to be entered there and dump just shows basically brew leaves.

+1 for this idea.

**Comment by ivank** [comment]
+1 From me too, when your Brewfile becomes hundreds of packages then managing that by hand becomes quite a chore. It would be great for this to be an option at least

**Comment by zackhsi** [comment]
+1 for leaves. 

https://robots.thoughtbot.com/brew-leaves
http://nvie.com/posts/better-package-management/

**Comment by mikemcquaid** [comment]
Thinking about it more: leaves won't work because it's a naive implementation which doesn't track if e.g. I uninstall a package but still want one of its dependencies.

> +1 From me too, when your Brewfile becomes hundreds of packages then managing that by hand becomes quite a chore. It would be great for this to be an option at least

Use `brew bundle dump` instead.

**Comment by jcrben** [comment]
Are you basically saying to use `brew bundle dump` instead of managing your Brewfile by hand? I don't want to manage my Brewfile by hand, but I do like it to be a manageable list as it reminds me of important software. I understand the issue with leaves, although I wish homebrew handled explicitly-installed packages better.

**Comment by mikemcquaid** [comment]
> Are you basically saying to use brew bundle dump instead of managing your Brewfile by hand? 

Yes.

> I understand the issue with leaves, although I wish homebrew handled explicitly-installed packages better.

We'd welcome pull requests to improve this :wink:
