### ISSUE TITLE
Link command?

### ISSUE THREAD

**Issue by AlJohri** [Homebrew/homebrew-bundle#84]
To force all packages to use homebrew's version of openssl, scripts often include

```
brew unlink openssl && brew link openssl --force
```

Is there any scope for a ```link``` and ```unlink``` command in the dsl?

**Comment by mikemcquaid** [comment]
I'm :-1:; it's often a bad idea and feels like a weird concern for `homebrew-bundle` to have.

**Comment by mikemcquaid** [comment]
Passing on this.

**Comment by jcarbo** [comment]
Just wondering if anything has changed on this in the last 1.5 years. Whether using `link` is a good/bad idea may be up for discussion, but when it's necessary there's no way around it.

I'm trying to use `homebrew-bundle` to maintain a one-command setup of an environment. If a package needs to be `link`ed, imho that's part of the configuration. Therefore, it'd be nice to be able to specify that within the `Brewfile` vs inside a script wrapping `brew bundle`. 

Something like:
```ruby
brew 'qt55', link: true
# or
brew 'qt55', link: :force
```

**Comment by MikeMcQuaid** [comment]
@jcarbo There's no reason things "have" to be linked. Linking something keg_only is generally a sign of bad configuration with the software that demands things be in `/usr/local` and that's the issue that should be fixed. Instead of this being in `brew bundle` I'd suggest you use a wrapper script which runs the `brew link`s as desired (but ideally request the upstream software be fixed).
