### ISSUE TITLE
Support for brew pip

### ISSUE THREAD

**Issue by nwhistler** [Homebrew/homebrew-bundle#976]
Hi, I was wondering if you could add support for [brew-pip ](https://github.com/hanxue/brew-pip) so that it could be used on a brewfile to add python packages with pip. 

Thank you,

**Comment by colindean** [comment]
Thanks for the suggestion.

I _think_ I'd prefer to see commonly-installed `pip` packages repackaged as brew formulae ala [some of these](https://github.com/Homebrew/homebrew-core/search?q=pip) via `brew create --python` instead of this but I'm open to the idea if other maintainers are interested. 

[brew-pip has a formula itself](https://github.com/Homebrew/homebrew-core/blob/master/Formula/brew-pip.rb) but it looks like it's not been maintained for several years despite [several hundred installs per month](https://formulae.brew.sh/formula/brew-pip#default).

Personally, `brew-pip` _might_ have a place in my workflow right now. I'm actively working a Python codebase for the first time in my professional life and have a Make task that handles dev env dependencies that looks _something_ like this (but a lot fancier with some command output detection):

```Makefile
deps: ## Install dependencies
	brew bundle
	pyenv install $(PYTHON_VERSION)
	pyenv local $(PYTHON_VERSION)
	$(PIP) install --upgrade \
		--index-url $(PYPI_PROXY) \
		pip
	$(PIP) install --upgrade \
		--index-url $(PYPI_PROXY) \
		poetry
	$(POETRY) install
```

With that in mind, this is for developing on a Python codebase, not just installing a tool that happens to be packaged and available only via PyPI.

The idea I return to is this: why not have brew bundle run `pip install --upgrade --requirement requirements.txt` after running, and if it'd be just doing that, why would that need to be a functionality of homebrew-bundle when it could be a part of a setup script that runs only when `brew bundle` exited successfully?

**Comment by nwhistler** [comment]
Yeah, the option at the bottom is a good idea. I've been using a brewfile because I can't remember all the things I install and need, so I document why I am installing it and keep it checked into my personal repo. I've also been doing this because my work computer has died a few times or the last number of years and so this makes setup up a new computer a dream.

I am working on some python scripting for some automation with selenium and rather than try to remember, I thought it would be nice to include it into my brewfile.

**Comment by jacobbednarz** [comment]
I'm a 👎 on this inclusion. It seems like a better fit is a language based package manager (such as bundler for Ruby or cargo for Rust) as that also covers other uses like installing specific versions which brew doesn't intentionally do. 

If you're after a consistent experience with scripts for repositories, a pattern like https://github.com/github/scripts-to-rule-them-all is a good start (can be achieved in any language really as long as it is executable).

**Comment by MikeMcQuaid** [comment]
> I _think_ I'd prefer to see commonly-installed `pip` packages repackaged as brew formulae ala [some of these](https://github.com/Homebrew/homebrew-core/search?q=pip) via `brew create --python` instead of this but I'm open to the idea if other maintainers are interested.

For libraries: not unless they have C components and/or a non-trivial number of code formulae depending on them.

I'm neutral on this idea, no strong opposition but I'd want to see a few more people need this and `brew pip` look a bit more maintained so: passing on this for now, sorry!
